FROM node:latest

ARG VERSION
ARG NAME
ARG ARCH

RUN echo ${VERSION} && \
    echo ${NAME} && \
    echo ${ARCH}

RUN node --version && \
    npm --version && \
    apt-get update

WORKDIR /opt/${NAME}

COPY source/config ./config
COPY source/templates ./config/templates
COPY README.md ./README.txt
COPY LICENSE ./LICENSE.txt
COPY CHANGELOG.md ./CHANGELOG.txt

WORKDIR /opt/${NAME}/code

COPY package.json package.json
COPY tsconfig.json tsconfig.json
COPY source ./source

RUN npm install

RUN ./node_modules/.bin/tsc --project ./tsconfig.json

RUN ./node_modules/.bin/pkg --silent --targets latest-macos-${ARCH} ./build/main.js --output ./../${NAME}-${VERSION}-macos-${ARCH}

WORKDIR /opt/${NAME}

RUN rm -rf code

RUN pwd
RUN ls -la

RUN chmod +x ${NAME}-${VERSION}-macos-${ARCH}

ENTRYPOINT /opt/${NAME}/${NAME}-${VERSION}-macos-${ARCH}