FROM mcr.microsoft.com/windows/servercore:ltsc2019

ARG VERSION
ARG NAME
ARG ARCH

RUN echo %VERSION% && \
    echo %NAME% && \
    echo %ARCH%

RUN powershell Set-ExecutionPolicy Bypass -Scope Process -Force
RUN powershell [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
RUN powershell [System.Net.WebRequest]::DefaultWebProxy.Credentials = [System.Net.CredentialCache]::DefaultCredentials
RUN powershell iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

RUN choco install -y --force nodejs

RUN node --version && \
    npm --version

WORKDIR /opt/${NAME}

RUN echo %cd%

COPY source/config ./config
COPY source/templates ./config/templates
COPY README.md ./README.txt
COPY LICENSE ./LICENSE.txt
COPY CHANGELOG.md ./CHANGELOG.txt

WORKDIR /opt/${NAME}/code

COPY package.json package.json
COPY tsconfig.json tsconfig.json
COPY source ./source

RUN npm install

RUN .\node_modules\.bin\tsc --project tsconfig.json

RUN .\node_modules\.bin\pkg --silent --targets latest-win-%ARCH% .\build\main.js --output .\..\%NAME%-%VERSION%-win-%ARCH%.exe

WORKDIR /opt/${NAME}

RUN del /s /q /f code
RUN rmdir /s /q code

RUN echo %cd%
RUN dir

ENTRYPOINT /opt/%NAME%/%NAME%-%VERSION%-win-%ARCH%.exe